DEFINE   MEASURE '_Report Measures'[pbi_prm_Env] =     (/* USER DAX BEGIN */   Var A =SWITCH(True(),[prmEnv]="Dev"," – DEV",[prmEnv]="QA"," – QA","") Var B="ServiceNow Restricted" Return B&A  /* USER DAX END */)     VAR __DS0FilterTable =     TREATAS(     {"'018-Territory Geo Users'[My Team]"},     'Sales Leader - Show By_ON_PREM'[On Prem Show By Fields]    )     VAR __DS0FilterTable2 =     FILTER(     KEEPFILTERS(VALUES('025-Parent Opportunity'[Parent Forecast Category])),     NOT('025-Parent Opportunity'[Parent Forecast Category] IN {"Closed"})    )     VAR __DS0FilterTable3 =     TREATAS({25}, 'TOPN_New'[TopN])     VAR __DS0FilterTable4 =     TREATAS({"All"}, 'Time Period -Deals Closed In'[Value])     VAR __DS0FilterTable5 =     FILTER(     KEEPFILTERS(VALUES('001-Quarter'[Dynamic Quarter])),     AND(      '001-Quarter'[Dynamic Quarter] IN {"Current Quarter"},      '001-Quarter'[Dynamic Quarter] IN {"Previous Quarter-3",       "Previous Quarter-2",       "Previous Quarter-1",       "Previous Quarter",       "Current Quarter",       "Current Quarter+1",       "Current Quarter+2",       "Current Quarter+3",       "Current Quarter+4"}     )    )     VAR __DS0FilterTable6 =     TREATAS(     {"'_Datamodel Measures'[Linearity_Closed + Submitted]"},     'Sales Leader - Show By Linearity'[ShowBy Linearity_Sales Leader Forecast Fields]    )     VAR __DS0FilterTable7 =     TREATAS({"'_Datamodel Measures'[OpenBuild (M)]"}, 'Metrics Parameter'[Parameter Fields])     VAR __DS0FilterTable8 =     TREATAS(     {"'018-Territory Geo Users'[My Team]"},     'Sales Leader - Show By'[Sales Leader - Show By Fields]    )    EVALUATE   SUMMARIZECOLUMNS(    __DS0FilterTable,    __DS0FilterTable2,    __DS0FilterTable3,    __DS0FilterTable4,    __DS0FilterTable5,    __DS0FilterTable6,    __DS0FilterTable7,    __DS0FilterTable8,    "pbi_prm_Env", IGNORE('_Report Measures'[pbi_prm_Env])   )