"""Build the 'Datagen Main.Notebook' artifact for deployment via `fab import`.

Usage:
    python -m datagen build-notebook
    python -m datagen build-notebook --output-dir ./my-dist
"""

import json
import os
import shutil

# Target environment — embedded in notebooks since they're not in git
_WORKSPACE_ID = "5de52008-bfaf-4e48-882e-d18ec06496fd"
_LAKEHOUSE_ID = "330a295b-8f5c-402d-816a-dc4911d751b8"
_LAKEHOUSE_NAME = "sld_lakehouse_import"

_LAKEHOUSE_METADATA = {
    "dependencies": {
        "lakehouse": {
            "default_lakehouse": _LAKEHOUSE_ID,
            "default_lakehouse_name": _LAKEHOUSE_NAME,
            "default_lakehouse_workspace_id": _WORKSPACE_ID,
        }
    }
}

_PYSPARK_METADATA = {
    "language_info": {"name": "python"},
    "kernel_info": {"name": "synapse_pyspark"},
    "kernelspec": {"display_name": "synapse_pyspark", "name": "synapse_pyspark"},
    "microsoft": {"language": "python", "language_group": "synapse_pyspark"},
    **_LAKEHOUSE_METADATA,
}

_PYTHON_METADATA = {
    "language_info": {"name": "python"},
    "kernel_info": {"name": "python"},
    "kernelspec": {"display_name": "Python 3", "name": "python3", "language": "python"},
    "microsoft": {"language": "python", "language_group": "python"},
    **_LAKEHOUSE_METADATA,
}


def build_notebook(output_dir=None):
    """Build the Fabric notebook artifact.

    Args:
        output_dir: Directory to write the notebook artifact.
                    Default: dist/ relative to current working directory.
    """
    if output_dir is None:
        output_dir = os.path.join(os.getcwd(), "dist")

    nb_dir = os.path.join(output_dir, "Datagen Main.Notebook")
    if os.path.exists(nb_dir):
        shutil.rmtree(nb_dir)
    os.makedirs(nb_dir)

    cells = [
        # ── Markdown: title ──
        {
            "cell_type": "markdown",
            "source": [
                "# Datagen\n",
                "\n",
                "Generate realistic Delta tables and a Direct Lake semantic model from a Power BI `.vpax` file.\n",
                "\n",
                "## Setup\n",
                "\n",
                "1. **Attach a Lakehouse** — click the Lakehouse icon in the left sidebar and select (or create) a Lakehouse\n",
                "2. **Upload your `.vpax` file** — place it in `Files/datagen/` in the attached Lakehouse\n",
                "   - Export a `.vpax` from [DAX Studio](https://daxstudio.org/) → Advanced → Export Metrics\n",
                "3. **Run Cell 1** below to install datagen (auto-downloads from GitHub if needed)\n",
                "4. **Edit Cell 2** — change the `.vpax` filename to match yours\n",
                "5. **Run Cell 2** — generates Delta tables, deploys a semantic model, and prints a comparison report\n",
            ],
            "metadata": {},
        },
        # ── Code: setup ──
        {
            "cell_type": "code",
            "source": [
                "# Install datagen — downloads the latest release from GitHub if not cached locally\n",
                "import glob, subprocess, sys, os, urllib.request, json\n",
                "\n",
                "if not os.path.isdir('/lakehouse/default'):\n",
                "    raise RuntimeError(\n",
                "        'No lakehouse attached. Click the Lakehouse icon in the left sidebar, '\n",
                "        'then select or create a Lakehouse before running this notebook.'\n",
                "    )\n",
                "\n",
                'DATAGEN_DIR = "/lakehouse/default/Files/datagen"\n',
                "os.makedirs(DATAGEN_DIR, exist_ok=True)\n",
                "\n",
                "USE_LATEST = True  # Set False to use a cached .whl instead of downloading\n",
                "\n",
                "def _get_latest_whl():\n",
                '    api_url = "https://api.github.com/repos/dbrownems/datagen/releases/latest"\n',
                "    with urllib.request.urlopen(api_url) as resp:\n",
                "        release = json.loads(resp.read())\n",
                '    asset = next(a for a in release["assets"] if a["name"].endswith(".whl"))\n',
                '    local = f"{DATAGEN_DIR}/{asset[\'name\']}"\n',
                "    if not os.path.exists(local):\n",
                '        print(f"Downloading {asset[\'name\']} ...")\n',
                '        urllib.request.urlretrieve(asset["browser_download_url"], local)\n',
                "    return local\n",
                "\n",
                "if USE_LATEST:\n",
                "    whl = _get_latest_whl()\n",
                "else:\n",
                '    whls = sorted(glob.glob(f"{DATAGEN_DIR}/datagen_fabric-*.whl"))\n',
                "    whl = whls[-1] if whls else _get_latest_whl()\n",
                "\n",
                'print(f"Installing {os.path.basename(whl)}")\n',
                "subprocess.check_call([\n",
                '    sys.executable, "-m", "pip", "install", whl, "semantic-link-labs",\n',
                '    "-q", "--no-warn-conflicts", "--disable-pip-version-check", "--force-reinstall", "--no-deps",\n',
                "])\n",
                'subprocess.check_call([sys.executable, "-m", "pip", "install", "semantic-link-labs", "-q", "--no-warn-conflicts", "--disable-pip-version-check"])\n',
                'import datagen; print(f"Ready — datagen v{datagen.__version__}")\n',
                "\n",
                "# Verify the installed version matches the loaded version\n",
                "import importlib.metadata\n",
                "installed = importlib.metadata.version('datagen-fabric')\n",
                "loaded = datagen.__version__\n",
                "if installed != loaded:\n",
                "    raise RuntimeError(\n",
                "        f'Version mismatch: installed v{installed} but loaded v{loaded}. '\n",
                "        f'Please restart the Spark session (Session → Stop session) and re-run.'\n",
                "    )\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # ── Markdown: generate instructions ──
        {
            "cell_type": "markdown",
            "source": [
                "## Generate\n",
                "\n",
                "Edit the `.vpax` filename below, then run the cell. This will:\n",
                "\n",
                "1. **Parse** the `.vpax` and infer data distributions from column statistics\n",
                "2. **Generate** Delta tables matching the original row counts and cardinality\n",
                "3. **Deploy** a Direct Lake semantic model with all measures, relationships, and column metadata\n",
                "4. **Compare** the generated tables against the expected statistics and print a report\n",
                "\n",
                "### Options\n",
                "\n",
                "| Parameter | Default | Description |\n",
                "|---|---|---|\n",
                "| `mode` | `\"direct_lake\"` | `\"import\"` for Power Query import mode |\n",
                "| `deploy_model` | `True` | `False` to skip semantic model deployment |\n",
                "| `compare` | `True` | `False` to skip comparison report |\n",
                "| `overwrite_tables` | `True` | `False` to skip existing tables, only generate missing |\n",
                "| `overwrite_model` | `True` | `False` to fail if semantic model already exists |\n",
                "| `seed` | `42` | Random seed for reproducible generation |\n",
            ],
            "metadata": {},
        },
        # ── Code: generate ──
        {
            "cell_type": "code",
            "source": [
                "from datagen import generate\n",
                "\n",
                "VPAX_FILE = \"\"  # ← set your .vpax filename, or leave blank to auto-detect\n",
                "\n",
                "# Auto-detect: use the first .vpax file in the datagen folder\n",
                "if not VPAX_FILE:\n",
                "    vpax_files = sorted(glob.glob(f\"{DATAGEN_DIR}/*.vpax\"))\n",
                "    if not vpax_files:\n",
                "        raise FileNotFoundError(f\"No .vpax files found in {DATAGEN_DIR}. Upload one and re-run.\")\n",
                "    vpax_path = vpax_files[0]\n",
                "    print(f\"Auto-detected: {os.path.basename(vpax_path)}\")\n",
                "else:\n",
                "    vpax_path = f\"{DATAGEN_DIR}/{VPAX_FILE}\"\n",
                "\n",
                "report = generate(\n",
                "    spark,\n",
                "    vpax_path,\n",
                "    compare=False,\n",
                "    overwrite_tables=False,\n",
                "    overwrite_model=True,\n",
                ")",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
    ]

    notebook = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": _PYSPARK_METADATA,
        "cells": cells,
    }

    platform = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "Notebook", "displayName": "Datagen Main"},
        "config": {"version": "2.0", "logicalId": "00000000-0000-0000-0000-000000000000"},
    }

    with open(os.path.join(nb_dir, "notebook-content.ipynb"), "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    with open(os.path.join(nb_dir, ".platform"), "w", encoding="utf-8") as f:
        json.dump(platform, f, indent=2)

    print(f"Notebook built: {nb_dir}")
    return nb_dir


def build_load_notebook(output_dir=None):
    """Build the 'Datagen Load Test.Notebook' artifact."""
    if output_dir is None:
        output_dir = os.path.join(os.getcwd(), "dist")

    nb_dir = os.path.join(output_dir, "Datagen Load Test.Notebook")
    if os.path.exists(nb_dir):
        shutil.rmtree(nb_dir)
    os.makedirs(nb_dir)

    cells = [
        {
            "cell_type": "markdown",
            "source": [
                "# Datagen Load Test\n",
                "\n",
                "Runs DAX queries against a semantic model simulating concurrent Power BI users.\n",
                "\n",
                "## Prerequisites\n",
                "\n",
                "1. Upload `queries.json` and `users.json` to `Files/datagen/` in the attached lakehouse\n",
                "2. `queries.json`: array of DAX query strings\n",
                "3. `users.json`: array of `{\"email\": \"...\", \"role\": \"...\"}` objects\n",
                "4. The semantic model must have RLS rules using `CUSTOMDATA()`\n",
            ],
            "metadata": {},
        },
        # ── Cell 1: Configuration ──
        {
            "cell_type": "code",
            "source": [
                "# ── Configuration ──\n",
                'XMLA_ENDPOINT = "powerbi://api.powerbi.com/v1.0/myorg/dbrowne_sld"\n',
                'DATASET = "Sales Leader Dataset"\n',
                "DURATION_SECONDS = 60      # total test duration\n",
                "CONCURRENT_USERS = 100     # number of simulated concurrent users\n",
                "QUERIES_PER_BATCH = 1      # concurrent queries per user\n",
                "PAUSE_BETWEEN_ITERATIONS_MS = 1000  # pause between iterations (ms)\n",
                "PAUSE_BETWEEN_QUERIES_MS = 0        # pause after each query (ms), 0=no pause\n",
                "USER_RAMP_TIME_SEC = 30            # ramp users over this many seconds, 0=all at once\n",
                'TARGET_REPLICA = "readonly"  # "readonly" for read-only replica (scale-out), "" for default\n',
                'LOG_FILE_NAME = ""             # log filename (auto-generated if empty)\n',
            ],
            "execution_count": None, "outputs": [], "metadata": {"tags": ["parameters"]},
        },
        {
            "cell_type": "code",
            "source": [
                "# Download .whl and DLL from GitHub — disabled, deploy via OneLake explorer instead\n",
                "import subprocess, sys, os, glob, json\n",
                "\n",
                'DATAGEN_DIR = "/lakehouse/default/Files/datagen"\n',
                "DEPLOY_FROM_GITHUB = False\n",
                "\n",
                "if DEPLOY_FROM_GITHUB:\n",
                "    import urllib.request\n",
                '    api_url = "https://api.github.com/repos/dbrownems/datagen/releases/latest"\n',
                "    with urllib.request.urlopen(api_url) as resp:\n",
                "        release = json.loads(resp.read())\n",
                "\n",
                "    # Download .whl\n",
                '    whl_asset = next(a for a in release["assets"] if a["name"].endswith(".whl"))\n',
                '    whl_path = f"{DATAGEN_DIR}/{whl_asset[\'name\']}"\n',
                "    if not os.path.exists(whl_path):\n",
                '        urllib.request.urlretrieve(whl_asset["browser_download_url"], whl_path)\n',
                '        print(f"Downloaded {whl_asset[\'name\']}")\n',
                "\n",
                "    # Download DLL\n",
                '    dll_asset = next(a for a in release["assets"] if a["name"] == "DatagenQueryRunner.dll")\n',
                '    dll_path = f"{DATAGEN_DIR}/DatagenQueryRunner.dll"\n',
                "    if not os.path.exists(dll_path):\n",
                '        urllib.request.urlretrieve(dll_asset["browser_download_url"], dll_path)\n',
                '        print(f"Downloaded {dll_asset[\'name\']}")\n',
                "\n",
                '    print("GitHub deploy complete")\n',
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # ── Cell 3: Setup ──
        {
            "cell_type": "code",
            "source": [
                "# Install datagen and load queries/users\n",
                "\n",
                "# Install datagen from lakehouse\n",
                "whls = sorted(glob.glob(f\"{DATAGEN_DIR}/datagen_fabric-*.whl\"))\n",
                "if not whls:\n",
                "    raise FileNotFoundError(f\"No .whl found in {DATAGEN_DIR}. Deploy via OneLake explorer.\")\n",
                "whl = whls[-1]\n",
                "subprocess.check_call([\n",
                "    sys.executable, \"-m\", \"pip\", \"install\", whl,\n",
                "    \"-q\", \"--disable-pip-version-check\", \"--force-reinstall\", \"--no-deps\",\n",
                "])\n",
                "import datagen; print(f\"datagen v{datagen.__version__}\")\n",
                "\n",
                "# Load queries and users\n",
                'with open(f"{DATAGEN_DIR}/queries.json", "r") as f:\n',
                "    queries = json.load(f)\n",
                'with open(f"{DATAGEN_DIR}/users.json", "r") as f:\n',
                "    all_users = json.load(f)\n",
                "\n",
                "# Expand or trim users to match CONCURRENT_USERS\n",
                "users = [all_users[i % len(all_users)] for i in range(CONCURRENT_USERS)]\n",
                "\n",
                'print(f"Queries: {len(queries)}")\n',
                'print(f"Users: {len(users)} (from {len(all_users)} in users.json)")\n',
                'print(f"Duration: {DURATION_SECONDS}s")\n',
                'print(f"Concurrency: {QUERIES_PER_BATCH} queries/user")\n',
                "\n",
                "# Get access token\n",
                "import notebookutils\n",
                'token = notebookutils.credentials.getToken("pbi")\n',
                'print(f"Token acquired ({len(token)} chars)")\n',
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # ── Cell 4: Run Load Test ──
        {
            "cell_type": "code",
            "source": [
                "# Run the load test\n",
                "from pythonnet import load\n",
                "load('coreclr')\n",
                "import clr, os, json, time\n",
                "\n",
                "# Bootstrap CLR and ADOMD.NET via sempy (knows how to find the assemblies)\n",
                "import sempy.fabric as fabric\n",
                "fabric.create_tom_server()\n",
                "\n",
                'dll_path = os.path.join(DATAGEN_DIR, "DatagenQueryRunner.dll")\n',
                "clr.AddReference(dll_path)\n",
                "from Datagen import QueryRunner\n",
                "from System import Array, String\n",
                "\n",
                "# Version check — ensure DLL matches the datagen package\n",
                "import System.Reflection\n",
                "asm = System.Reflection.Assembly.GetAssembly(QueryRunner)\n",
                "dll_version = str(asm.GetName().Version)\n",
                "pkg_version = datagen.__version__\n",
                "# Compare major.minor.patch (DLL has 4-part version)\n",
                "dll_short = '.'.join(dll_version.split('.')[:3])\n",
                "if dll_short != pkg_version:\n",
                "    print(f'\u26a0 Version mismatch: DatagenQueryRunner.dll v{dll_short} vs datagen v{pkg_version}')\n",
                "    print(f'  Delete Files/datagen/DatagenQueryRunner.dll and re-run Cell 2 to update.')\n",
                "else:\n",
                "    print(f'QueryRunner v{dll_short} \u2713')\n",
                "\n",
                "# Build XMLA endpoint (append ?readonly for scale-out testing)\n",
                "xmla = f'{XMLA_ENDPOINT}?{TARGET_REPLICA}' if TARGET_REPLICA else XMLA_ENDPOINT\n",
                "\n",
                "# Prepare .NET arrays\n",
                "q_arr = Array[String]([q if isinstance(q, str) else q['query'] for q in queries])\n",
                "email_arr = Array[String]([u['email'] for u in users])\n",
                "role_arr = Array[String]([u['role'] for u in users])\n",
                "\n",
                'print(f"Starting load test: {len(users)} users \u00d7 {len(queries)} queries, {DURATION_SECONDS}s...")\n',
                "if TARGET_REPLICA:\n",
                '    print(f"Target: {TARGET_REPLICA} replica")\n',
                "print(flush=True)\n",
                "\n",
                "# Log directory for telemetry CSV\n",
                "LOG_DIR = f\"{DATAGEN_DIR}/logs\"\n",
                "os.makedirs(LOG_DIR, exist_ok=True)\n",
                "\n",
                "from datetime import datetime, timezone\n",
                "test_start_utc = datetime.now(timezone.utc)\n",
                "\n",
                "# Use provided log filename or auto-generate\n",
                "if not LOG_FILE_NAME:\n",
                "    cdt = test_start_utc.astimezone()\n",
                "    LOG_FILE_NAME = f\"LoadTest.{CONCURRENT_USERS}users.{cdt.strftime('%Y%m%d-%H%M%S')}.csv\"\n",
                "log_file_path = f\"{LOG_DIR}/{LOG_FILE_NAME}\"\n",
                "print(f\"Log file: {LOG_FILE_NAME}\")\n",
                "\n",
                "t0 = time.time()\n",
                "result_json = QueryRunner.RunLoadTest(\n",
                "    q_arr, xmla, DATASET, token,\n",
                "    email_arr, role_arr,\n",
                "    DURATION_SECONDS,\n",
                "    QUERIES_PER_BATCH,\n",
                "    PAUSE_BETWEEN_ITERATIONS_MS,\n",
                "    PAUSE_BETWEEN_QUERIES_MS,\n",
                "    LOG_DIR,\n",
                "    USER_RAMP_TIME_SEC,\n",
                "    LOG_FILE_NAME,\n",
                ")\n",
                "elapsed = time.time() - t0\n",
                "test_end_utc = datetime.now(timezone.utc)\n",
                "\n",
                "stats = json.loads(result_json)\n",
                'print(f"\\n=== Load Test Results ({elapsed:.0f}s) ===")\n',
                'print(f"Total executions: {stats[\'totalExecutions\']}")\n',
                'print(f"Successful:       {stats[\'successfulExecutions\']}")\n',
                'print(f"Failed:           {stats[\'failedExecutions\']}")\n',
                'print(f"QPS:              {stats[\'qps\']}")\n',
                'print(f"Max iteration:    {stats[\'maxIteration\']}")\n',
                "\n",
                "if 'latency' in stats:\n",
                "    lat = stats['latency']\n",
                '    print(f"\\nLatency:")\n',
                '    print(f"  Min:    {lat[\'min\']}ms")\n',
                '    print(f"  Median: {lat[\'median\']}ms")\n',
                '    print(f"  Mean:   {lat[\'mean\']}ms")\n',
                '    print(f"  P95:    {lat[\'p95\']}ms")\n',
                '    print(f"  P99:    {lat[\'p99\']}ms")\n',
                '    print(f"  Max:    {lat[\'max\']}ms")\n',
                "\n",
                'print(f"\\nPer-user:")\n',
                "for u in stats.get('perUser', []):\n",
                "    user = users[u['userIndex']]\n",
                '    print(f"  {user[\'email\'][:30]:30s} iters={u[\'iterations\']} execs={u[\'executions\']} errs={u[\'errors\']} avg={u[\'meanLatencyMs\']}ms")\n',
                "\n",
                "if 'sampleErrors' in stats:\n",
                '    print(f"\\nSample errors:")\n',
                "    for e in stats['sampleErrors']:\n",
                '        print(f"  User {e[\'UserIndex\']}, Q{e[\'QueryIndex\']}: {str(e[\'Error\'])[:100]}")\n',
                "\n",
                "# Save full results\n",
                'with open(f"{DATAGEN_DIR}/load_test_results.json", "w") as f:\n',
                "    json.dump(stats, f, indent=2)\n",
                'print(f"\\nFull results saved to Files/datagen/load_test_results.json")\n',
                "if 'logFile' in stats:\n",
                '    print(f"Telemetry log: {stats[\'logFile\']}")\n',
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # ── Cell 5: Telemetry Report ──
        {
            "cell_type": "code",
            "source": [
                "# Telemetry report — read the CSV log and chart query performance\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import glob, os, requests\n",
                "\n",
                "# Find the latest log file\n",
                "log_files = sorted(glob.glob(f\"{DATAGEN_DIR}/logs/LoadTest.*.csv\"))\n",
                "if not log_files:\n",
                "    raise FileNotFoundError('No log files found in Files/datagen/logs/')\n",
                "\n",
                "log_path = log_files[-1]\n",
                "print(f\"Reading: {os.path.basename(log_path)}\")\n",
                "df = pd.read_csv(log_path)\n",
                "print(f\"Records: {len(df)}  |  Success: {(df.Outcome=='Success').sum()}  |  Error: {(df.Outcome=='Error').sum()}\")\n",
                "\n",
                "# Compute time buckets (100 buckets across the test duration)\n",
                "t_min, t_max = df.StartTimeMs.min(), df.StartTimeMs.max()\n",
                "duration_s = (t_max - t_min) / 1000\n",
                "n_buckets = min(100, len(df))\n",
                "df['bucket'] = pd.cut(df.StartTimeMs, bins=n_buckets, labels=False)\n",
                "\n",
                "# Aggregate per bucket\n",
                "ok = df[df.Outcome == 'Success']\n",
                "err = df[df.Outcome == 'Error']\n",
                "agg = ok.groupby('bucket').agg(\n",
                "    count=('DurationMs', 'count'),\n",
                "    mean_ms=('DurationMs', 'mean'),\n",
                "    min_ms=('DurationMs', 'min'),\n",
                "    max_ms=('DurationMs', 'max'),\n",
                "    t=('StartTimeMs', 'mean'),\n",
                ").reset_index()\n",
                "err_agg = err.groupby('bucket').agg(err_count=('DurationMs', 'count')).reset_index()\n",
                "user_agg = df.groupby('bucket').agg(active_users=('ActiveUsers', 'max')).reset_index()\n",
                "agg = agg.merge(err_agg, on='bucket', how='left').merge(user_agg, on='bucket', how='left').fillna(0)\n",
                "agg['time_s'] = (agg.t - t_min) / 1000\n",
                "\n",
                "# Query refresh history for the test window\n",
                "refresh_times_s = []\n",
                "try:\n",
                "    import sempy.fabric as _fabric\n",
                "    from dateutil import parser as _dtp\n",
                "    _ws_id = _fabric.resolve_workspace_id()\n",
                "    _rh_headers = {'Authorization': f'Bearer {token}'}\n",
                "    _ds_resp = requests.get(f'https://api.powerbi.com/v1.0/myorg/groups/{_ws_id}/datasets', headers=_rh_headers)\n",
                "    _ds = next(d for d in _ds_resp.json()['value'] if d['name'] == DATASET)\n",
                "    _rh_resp = requests.get(f'https://api.powerbi.com/v1.0/myorg/groups/{_ws_id}/datasets/{_ds[\"id\"]}/refreshes?$top=10', headers=_rh_headers)\n",
                "    for r in _rh_resp.json().get('value', []):\n",
                "        rs = _dtp.isoparse(r.get('startTime', '1970-01-01T00:00:00Z'))\n",
                "        re = _dtp.isoparse(r['endTime']) if r.get('endTime') else test_end_utc\n",
                "        if rs <= test_end_utc and re >= test_start_utc:\n",
                "            offset_s = (rs - test_start_utc).total_seconds()\n",
                "            refresh_times_s.append((max(0, offset_s), r))\n",
                "except Exception as ex:\n",
                "    print(f'Could not check refresh history: {ex}')\n",
                "\n",
                "fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 10), sharex=True,\n",
                "                                    gridspec_kw={'height_ratios': [3, 1, 1]})\n",
                "\n",
                "# Top: latency\n",
                "ax1.fill_between(agg.time_s, agg.min_ms, agg.max_ms, alpha=0.15, color='steelblue', label='min\\u2013max')\n",
                "ax1.plot(agg.time_s, agg.mean_ms, color='steelblue', linewidth=1.5, label='mean')\n",
                "ax1.plot(agg.time_s, agg.max_ms, color='coral', linewidth=0.8, alpha=0.7, label='max')\n",
                "for rt_s, _ in refresh_times_s:\n",
                "    ax1.axvline(x=rt_s, color='green', linestyle='--', linewidth=1.5, alpha=0.7)\n",
                "if refresh_times_s:\n",
                "    ax1.axvline(x=refresh_times_s[0][0], color='green', linestyle='--', linewidth=1.5, alpha=0.7, label='Refresh')\n",
                "ax1.set_ylabel('Latency (ms)')\n",
                "ax1.legend(loc='upper left')\n",
                "ax1.set_title(f'Load Test \\u2014 {len(df)} queries over {duration_s:.0f}s')\n",
                "ax1.grid(True, alpha=0.3)\n",
                "\n",
                "# Middle: throughput\n",
                "bucket_width = duration_s / n_buckets\n",
                "ax2.bar(agg.time_s, agg['count'] / bucket_width, width=bucket_width * 0.9,\n",
                "        color='steelblue', alpha=0.6, label='QPS (success)')\n",
                "if agg.err_count.sum() > 0:\n",
                "    ax2.bar(agg.time_s, agg.err_count / bucket_width, width=bucket_width * 0.9,\n",
                "            bottom=agg['count'] / bucket_width, color='red', alpha=0.6, label='QPS (error)')\n",
                "for rt_s, _ in refresh_times_s:\n",
                "    ax2.axvline(x=rt_s, color='green', linestyle='--', linewidth=1.5, alpha=0.7)\n",
                "ax2.set_ylabel('Queries/sec')\n",
                "ax2.legend(loc='upper left')\n",
                "ax2.grid(True, alpha=0.3)\n",
                "\n",
                "# Bottom: active users\n",
                "ax3.plot(agg.time_s, agg.active_users, color='green', linewidth=1.5, label='Active users')\n",
                "ax3.fill_between(agg.time_s, 0, agg.active_users, alpha=0.1, color='green')\n",
                "for rt_s, _ in refresh_times_s:\n",
                "    ax3.axvline(x=rt_s, color='green', linestyle='--', linewidth=1.5, alpha=0.7)\n",
                "ax3.set_ylabel('Users')\n",
                "ax3.set_xlabel('Time (seconds)')\n",
                "ax3.legend(loc='upper left')\n",
                "ax3.grid(True, alpha=0.3)\n",
                "ax3.set_ylim(bottom=0)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# Summary stats\n",
                "print(f\"\\nDuration: {duration_s:.1f}s\")\n",
                "print(f\"QPS: {(df.Outcome=='Success').sum() / duration_s:.1f}\")\n",
                "print(f\"Users: {df.UserEmail.nunique()} distinct\")\n",
                "print(f\"Latency \\u2014 min: {ok.DurationMs.min():.0f}ms  median: {ok.DurationMs.median():.0f}ms  \"\n",
                "      f\"mean: {ok.DurationMs.mean():.0f}ms  p95: {ok.DurationMs.quantile(0.95):.0f}ms  \"\n",
                "      f\"max: {ok.DurationMs.max():.0f}ms\")\n",
                "\n",
                "# Refreshes during test\n",
                "if refresh_times_s:\n",
                "    print(f\"\\nRefreshes during test ({len(refresh_times_s)}):\")\n",
                "    for rt_s, r in refresh_times_s:\n",
                "        print(f\"  t={rt_s:.0f}s  {r.get('startTime','?')} \\u2192 {r.get('endTime','in progress')}  status={r.get('status','?')}\")\n",
                "else:\n",
                "    print('\\nNo model refreshes during test window')\n",
                "print(f'Test window: {test_start_utc.isoformat()} \\u2192 {test_end_utc.isoformat()}')\n",
                "\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
    ]

    notebook = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": _PYTHON_METADATA,
        "cells": cells,
    }

    platform = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "Notebook", "displayName": "Datagen Load Test"},
        "config": {"version": "2.0", "logicalId": "11111111-1111-1111-1111-111111111111"},
    }

    with open(os.path.join(nb_dir, "notebook-content.ipynb"), "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    with open(os.path.join(nb_dir, ".platform"), "w", encoding="utf-8") as f:
        json.dump(platform, f, indent=2)

    print(f"Notebook built: {nb_dir}")
    return nb_dir


def build_scaleout_notebook(output_dir=None):
    """Build the 'Datagen Scale-Out Test.Notebook' artifact."""
    if output_dir is None:
        output_dir = os.path.join(os.getcwd(), "dist")

    nb_dir = os.path.join(output_dir, "Datagen Scale-Out Test.Notebook")
    if os.path.exists(nb_dir):
        shutil.rmtree(nb_dir)
    os.makedirs(nb_dir)

    cells = [
        {
            "cell_type": "markdown",
            "source": [
                "# Datagen Scale-Out Test\n",
                "\n",
                "Configure a semantic model for scale-out with manual sync, then trigger refresh and sync.\n",
                "\n",
                "**Scenario:** Run alongside the Load Test notebook to measure the impact of refresh + sync\n",
                "on an active query workload hitting the read-only replica.\n",
                "\n",
                "## Workflow\n",
                "\n",
                "1. **Cell 1** \u2014 Configure: set workspace and dataset, acquire token\n",
                "2. **Cell 2** \u2014 Enable scale-out with manual sync (one-time setup)\n",
                "3. **Cell 3** \u2014 Check sync status\n",
                "4. Start the **Load Test** notebook (with `TARGET_REPLICA = \"readonly\"`)\n",
                "5. **Cell 4** \u2014 Trigger refresh on the read/write node and wait\n",
                "6. **Cell 5** \u2014 Trigger manual sync to propagate to read-only replicas\n",
                "7. **Cell 6** \u2014 Disable scale-out (cleanup when done)\n",
            ],
            "metadata": {},
        },
        # -- Cell 1: Configuration --
        {
            "cell_type": "code",
            "source": [
                "# -- Configuration --\n",
                "import requests, json, time\n",
                "import notebookutils\n",
                "\n",
                "WORKSPACE_ID = \"5de52008-bfaf-4e48-882e-d18ec06496fd\"\n",
                "DATASET_NAME = \"Sales Leader Dataset\"\n",
                "\n",
                "# Acquire Power BI token\n",
                "token = notebookutils.credentials.getToken(\"pbi\")\n",
                "headers = {\"Authorization\": f\"Bearer {token}\", \"Content-Type\": \"application/json\"}\n",
                "BASE = \"https://api.powerbi.com/v1.0/myorg\"\n",
                "\n",
                "# Find dataset ID\n",
                "resp = requests.get(f\"{BASE}/groups/{WORKSPACE_ID}/datasets\", headers=headers)\n",
                "resp.raise_for_status()\n",
                "dataset = next(d for d in resp.json()['value'] if d['name'] == DATASET_NAME)\n",
                "DATASET_ID = dataset['id']\n",
                "\n",
                "# Check current scale-out config\n",
                "resp = requests.get(f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}\", headers=headers)\n",
                "resp.raise_for_status()\n",
                "qso = resp.json().get('queryScaleOutSettings', {})\n",
                "\n",
                "print(f\"Dataset: {DATASET_NAME}\")\n",
                "print(f\"Dataset ID: {DATASET_ID}\")\n",
                "print(f\"Scale-out: maxReadOnlyReplicas={qso.get('maxReadOnlyReplicas')}, \"\n",
                "      f\"autoSync={qso.get('autoSyncReadOnlyReplicas')}\")\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # -- Cell 2: Enable Scale-Out --
        {
            "cell_type": "code",
            "source": [
                "# Enable scale-out with manual sync\n",
                "body = {\n",
                "    \"queryScaleOutSettings\": {\n",
                "        \"maxReadOnlyReplicas\": -1,\n",
                "        \"autoSyncReadOnlyReplicas\": False\n",
                "    }\n",
                "}\n",
                "resp = requests.patch(\n",
                "    f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}\",\n",
                "    headers=headers, json=body\n",
                ")\n",
                "resp.raise_for_status()\n",
                "\n",
                "# Verify\n",
                "resp = requests.get(f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}\", headers=headers)\n",
                "resp.raise_for_status()\n",
                "qso = resp.json().get('queryScaleOutSettings', {})\n",
                "replicas = qso.get('maxReadOnlyReplicas', 0)\n",
                "auto_sync = qso.get('autoSyncReadOnlyReplicas', True)\n",
                "\n",
                "print(f\"maxReadOnlyReplicas: {replicas}\")\n",
                "print(f\"autoSyncReadOnlyReplicas: {auto_sync}\")\n",
                "if replicas != 0 and not auto_sync:\n",
                "    print(\"\\u2713 Scale-out enabled with manual sync\")\n",
                "else:\n",
                "    print(\"\\u26a0 Configuration may not be correct\")\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # -- Cell 3: Check Sync Status --
        {
            "cell_type": "code",
            "source": [
                "# Check sync status\n",
                "resp = requests.get(\n",
                "    f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}/queryScaleOut/syncStatus\",\n",
                "    headers=headers\n",
                ")\n",
                "resp.raise_for_status()\n",
                "status = resp.json()\n",
                "print(json.dumps(status, indent=2))\n",
                "\n",
                "if status.get('commitVersion') == status.get('minActiveReadVersion'):\n",
                "    print(\"\\n\\u2713 Read-write and read-only replicas are in sync\")\n",
                "else:\n",
                "    print(f\"\\n\\u26a0 Out of sync: commit v{status.get('commitVersion')} \"\n",
                "          f\"vs read v{status.get('minActiveReadVersion')}\")\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # -- Cell 4: Trigger Refresh --
        {
            "cell_type": "code",
            "source": [
                "# Trigger a full refresh on the read/write node\n",
                "# With manual sync, this does NOT affect read-only replicas until sync\n",
                "resp = requests.post(\n",
                "    f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}/refreshes\",\n",
                "    headers=headers, json={\"type\": \"full\"}\n",
                ")\n",
                "print(f\"Refresh triggered: HTTP {resp.status_code}\")\n",
                "resp.raise_for_status()\n",
                "\n",
                "# Poll for refresh completion\n",
                "print(\"Waiting for refresh to complete\", end=\"\", flush=True)\n",
                "while True:\n",
                "    time.sleep(10)\n",
                "    print(\".\", end=\"\", flush=True)\n",
                "    resp = requests.get(\n",
                "        f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}/refreshes?$top=1\",\n",
                "        headers=headers\n",
                "    )\n",
                "    resp.raise_for_status()\n",
                "    refreshes = resp.json().get('value', [])\n",
                "    if refreshes and refreshes[0].get('status') != 'Unknown':\n",
                "        print()\n",
                "        rstat = refreshes[0]['status']\n",
                "        if rstat == 'Completed':\n",
                "            print(f\"\\u2713 Refresh completed\")\n",
                "        else:\n",
                "            print(f\"\\u26a0 Refresh status: {rstat}\")\n",
                "            if 'serviceExceptionJson' in refreshes[0]:\n",
                "                print(refreshes[0]['serviceExceptionJson'])\n",
                "        break\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # -- Cell 5: Trigger Sync --
        {
            "cell_type": "code",
            "source": [
                "# Trigger manual sync to propagate refresh to read-only replicas\n",
                "resp = requests.post(\n",
                "    f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}/queryScaleOut/sync\",\n",
                "    headers=headers, data=\"\"\n",
                ")\n",
                "print(f\"Sync triggered: HTTP {resp.status_code}\")\n",
                "resp.raise_for_status()\n",
                "\n",
                "# Poll for sync completion\n",
                "print(\"Waiting for sync to complete\", end=\"\", flush=True)\n",
                "while True:\n",
                "    time.sleep(5)\n",
                "    print(\".\", end=\"\", flush=True)\n",
                "    resp = requests.get(\n",
                "        f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}/queryScaleOut/syncStatus\",\n",
                "        headers=headers\n",
                "    )\n",
                "    resp.raise_for_status()\n",
                "    status = resp.json()\n",
                "    if status.get('commitVersion') == status.get('minActiveReadVersion'):\n",
                "        print()\n",
                "        print(f\"\\u2713 Sync completed\")\n",
                "        print(f\"  syncStartTime: {status.get('syncStartTime')}\")\n",
                "        print(f\"  syncEndTime: {status.get('syncEndTime')}\")\n",
                "        break\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # -- Cell 6: Disable Scale-Out --
        {
            "cell_type": "code",
            "source": [
                "# Disable scale-out (run when done with testing)\n",
                "body = {\"queryScaleOutSettings\": {\"maxReadOnlyReplicas\": 0}}\n",
                "resp = requests.patch(\n",
                "    f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}\",\n",
                "    headers=headers, json=body\n",
                ")\n",
                "resp.raise_for_status()\n",
                "\n",
                "# Verify\n",
                "resp = requests.get(f\"{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}\", headers=headers)\n",
                "resp.raise_for_status()\n",
                "qso = resp.json().get('queryScaleOutSettings', {})\n",
                "if qso.get('maxReadOnlyReplicas', -1) == 0:\n",
                "    print(\"\\u2713 Scale-out disabled\")\n",
                "else:\n",
                "    print(f\"\\u26a0 Still enabled: {qso}\")\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
    ]

    notebook = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": _PYTHON_METADATA,
        "cells": cells,
    }

    platform = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "Notebook", "displayName": "Datagen Scale-Out Test"},
        "config": {"version": "2.0", "logicalId": "22222222-2222-2222-2222-222222222222"},
    }

    with open(os.path.join(nb_dir, "notebook-content.ipynb"), "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    with open(os.path.join(nb_dir, ".platform"), "w", encoding="utf-8") as f:
        json.dump(platform, f, indent=2)

    print(f"Notebook built: {nb_dir}")
    return nb_dir


def build_refresh_notebook(output_dir=None):
    """Build the 'Datagen Refresh Model.Notebook' artifact."""
    if output_dir is None:
        output_dir = os.path.join(os.getcwd(), "dist")

    nb_dir = os.path.join(output_dir, "Datagen Refresh Model.Notebook")
    if os.path.exists(nb_dir):
        shutil.rmtree(nb_dir)
    os.makedirs(nb_dir)

    cells = [
        {
            "cell_type": "markdown",
            "source": [
                "# Datagen Refresh Model\n",
                "\n",
                "Periodically refresh the target semantic model and log refresh/sync timing.\n",
                "\n",
                "**Workflow:** Start this notebook alongside the Load Test notebook.\n",
                "It waits for the ramp-up period, then performs periodic refreshes,\n",
                "logging each refresh and sync cycle to a CSV in Files/datagen/logs/.\n",
            ],
            "metadata": {},
        },
        # -- Cell 1: Configuration --
        {
            "cell_type": "code",
            "source": [
                "# -- Configuration --\n",
                "DATASET = \"Sales Leader Dataset\"\n",
                "TABLES = [\"017-Date\"]           # list of tables, or None for full refresh\n",
                "INITIAL_DELAY_SEC = 600          # wait before first refresh (default 10 min)\n",
                "REFRESH_INTERVAL_SEC = 300       # time between refreshes (default 5 min)\n",
                "TOTAL_DURATION_SEC = 1800        # total run time (default 30 min)\n",
                "SYNC_POLL_SEC = 5                # poll sync status every N seconds\n",
                "LOG_FILE_NAME = \"\"               # log filename (auto-generated if empty)\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {"tags": ["parameters"]},
        },
        # -- Cell 2: Setup --
        {
            "cell_type": "code",
            "source": [
                "# Setup\n",
                "import subprocess, sys, os, time, csv\n",
                "subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"semantic-link-labs\",\n",
                "    \"-q\", \"--no-warn-conflicts\", \"--disable-pip-version-check\"])\n",
                "import sempy_labs as labs\n",
                "import sempy.fabric as fabric\n",
                "import requests\n",
                "from datetime import datetime, timezone\n",
                "import notebookutils\n",
                "\n",
                "WORKSPACE = fabric.resolve_workspace_name()\n",
                "WORKSPACE_ID = fabric.resolve_workspace_id()\n",
                "DATAGEN_DIR = \"/lakehouse/default/Files/datagen\"\n",
                "LOG_DIR = f\"{DATAGEN_DIR}/logs\"\n",
                "os.makedirs(LOG_DIR, exist_ok=True)\n",
                "\n",
                "# Find dataset ID\n",
                "token = notebookutils.credentials.getToken(\"pbi\")\n",
                "headers = {\"Authorization\": f\"Bearer {token}\", \"Content-Type\": \"application/json\"}\n",
                "BASE = \"https://api.powerbi.com/v1.0/myorg\"\n",
                "ds_resp = requests.get(f\"{BASE}/groups/{WORKSPACE_ID}/datasets\", headers=headers)\n",
                "ds_resp.raise_for_status()\n",
                "DATASET_ID = next(d for d in ds_resp.json()['value'] if d['name'] == DATASET)['id']\n",
                "\n",
                "print(f\"Dataset: {DATASET} ({DATASET_ID})\")\n",
                "print(f\"Workspace: {WORKSPACE}\")\n",
                "print(f\"Tables: {TABLES or 'Full refresh'}\")\n",
                "print(f\"Initial delay: {INITIAL_DELAY_SEC}s, interval: {REFRESH_INTERVAL_SEC}s, duration: {TOTAL_DURATION_SEC}s\")\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # -- Cell 3: Refresh Loop --
        {
            "cell_type": "code",
            "source": [
                "# Refresh loop with logging\n",
                "notebook_start = datetime.now(timezone.utc)\n",
                "cdt = notebook_start.astimezone()\n",
                "if not LOG_FILE_NAME:\n",
                "    LOG_FILE_NAME = f\"RefreshHistory.{cdt.strftime('%Y%m%d-%H%M%S')}.csv\"\n",
                "log_file = os.path.join(LOG_DIR, LOG_FILE_NAME)\n",
                "\n",
                "# Write CSV header\n",
                "with open(log_file, 'w', newline='') as f:\n",
                "    writer = csv.writer(f)\n",
                "    writer.writerow(['RefreshNumber', 'RefreshStartUTC', 'RefreshEndUTC', 'RefreshDurationSec',\n",
                "                     'RefreshStatus', 'SyncStartUTC', 'SyncEndUTC', 'SyncDurationSec'])\n",
                "print(f\"Logging to: {log_file}\")\n",
                "\n",
                "def get_token():\n",
                "    t = notebookutils.credentials.getToken('pbi')\n",
                "    return {'Authorization': f'Bearer {t}', 'Content-Type': 'application/json'}\n",
                "\n",
                "def poll_sync(h):\n",
                "    \"\"\"Poll sync status until replicas are in sync. Returns (sync_start, sync_end).\"\"\"\n",
                "    while True:\n",
                "        r = requests.get(f'{BASE}/groups/{WORKSPACE_ID}/datasets/{DATASET_ID}/queryScaleOut/syncStatus', headers=h)\n",
                "        r.raise_for_status()\n",
                "        s = r.json()\n",
                "        if s.get('commitVersion') == s.get('minActiveReadVersion'):\n",
                "            return s.get('syncStartTime', ''), s.get('syncEndTime', '')\n",
                "        time.sleep(SYNC_POLL_SEC)\n",
                "\n",
                "# Wait for initial delay\n",
                "print(f\"Waiting {INITIAL_DELAY_SEC}s before first refresh...\", flush=True)\n",
                "time.sleep(INITIAL_DELAY_SEC)\n",
                "\n",
                "deadline = time.time() + TOTAL_DURATION_SEC\n",
                "refresh_num = 0\n",
                "\n",
                "while time.time() < deadline:\n",
                "    refresh_num += 1\n",
                "    h = get_token()\n",
                "\n",
                "    # Trigger refresh\n",
                "    refresh_start = datetime.now(timezone.utc)\n",
                "    print(f\"\\nRefresh #{refresh_num} at {refresh_start.strftime('%H:%M:%S')} UTC\", flush=True)\n",
                "    try:\n",
                "        labs.refresh_semantic_model(dataset=DATASET, workspace=WORKSPACE, tables=TABLES)\n",
                "    except Exception as ex:\n",
                "        print(f\"  Refresh failed: {ex}\")\n",
                "        refresh_end = datetime.now(timezone.utc)\n",
                "        with open(log_file, 'a', newline='') as f:\n",
                "            csv.writer(f).writerow([refresh_num,\n",
                "                refresh_start.isoformat(), refresh_end.isoformat(),\n",
                "                f'{(refresh_end - refresh_start).total_seconds():.1f}',\n",
                "                'Failed', '', '', ''])\n",
                "        time.sleep(REFRESH_INTERVAL_SEC)\n",
                "        continue\n",
                "\n",
                "    refresh_end = datetime.now(timezone.utc)\n",
                "    refresh_dur = (refresh_end - refresh_start).total_seconds()\n",
                "    print(f\"  Refresh completed in {refresh_dur:.1f}s\", flush=True)\n",
                "\n",
                "    # Poll for sync\n",
                "    print(f\"  Waiting for sync...\", end='', flush=True)\n",
                "    h = get_token()\n",
                "    sync_start_str, sync_end_str = poll_sync(h)\n",
                "    print(f\" done\")\n",
                "    print(f\"  Sync: {sync_start_str} \\u2192 {sync_end_str}\")\n",
                "\n",
                "    # Log to CSV\n",
                "    from dateutil import parser as dtp\n",
                "    try:\n",
                "        sync_dur = (dtp.isoparse(sync_end_str) - dtp.isoparse(sync_start_str)).total_seconds()\n",
                "    except Exception:\n",
                "        sync_dur = ''\n",
                "    with open(log_file, 'a', newline='') as f:\n",
                "        csv.writer(f).writerow([refresh_num,\n",
                "            refresh_start.isoformat(), refresh_end.isoformat(),\n",
                "            f'{refresh_dur:.1f}', 'Completed',\n",
                "            sync_start_str, sync_end_str,\n",
                "            f'{sync_dur:.1f}' if isinstance(sync_dur, float) else ''])\n",
                "\n",
                "    # Wait for next interval\n",
                "    elapsed = (datetime.now(timezone.utc) - refresh_start).total_seconds()\n",
                "    wait = max(0, REFRESH_INTERVAL_SEC - elapsed)\n",
                "    if time.time() + wait >= deadline:\n",
                "        break  # not enough time for another full cycle\n",
                "    if wait > 0:\n",
                "        print(f\"  Next refresh in {wait:.0f}s\")\n",
                "        time.sleep(wait)\n",
                "\n",
                "print(f\"\\n\\u2713 Refresh loop complete. {refresh_num} refreshes performed.\")\n",
                "print(f\"Log: {log_file}\")\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
    ]

    notebook = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": _PYTHON_METADATA,
        "cells": cells,
    }

    platform = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "Notebook", "displayName": "Datagen Refresh Model"},
        "config": {"version": "2.0", "logicalId": "33333333-3333-3333-3333-333333333333"},
    }

    with open(os.path.join(nb_dir, "notebook-content.ipynb"), "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    with open(os.path.join(nb_dir, ".platform"), "w", encoding="utf-8") as f:
        json.dump(platform, f, indent=2)

    print(f"Notebook built: {nb_dir}")
    return nb_dir


def build_driver_notebook(output_dir=None):
    """Build the 'Datagen Run Load Test With Refreshes.Notebook' artifact."""
    if output_dir is None:
        output_dir = os.path.join(os.getcwd(), "dist")

    nb_dir = os.path.join(output_dir, "Datagen Run Load Test With Refreshes.Notebook")
    if os.path.exists(nb_dir):
        shutil.rmtree(nb_dir)
    os.makedirs(nb_dir)

    cells = [
        {
            "cell_type": "markdown",
            "source": [
                "# Run Load Test With Refreshes\n",
                "\n",
                "Runs the Load Test and Refresh Model notebooks concurrently.\n",
                "The Refresh notebook waits for the ramp-up period before triggering refreshes.\n",
            ],
            "metadata": {},
        },
        {
            "cell_type": "code",
            "source": [
                "# -- Configuration --\n",
                "DURATION_SECONDS = 20*60        # total test duration\n",
                "USER_RAMP_TIME_SEC = 5*60       # ramp users over this many seconds\n",
                "CONCURRENT_USERS = 1000         # number of simulated concurrent users\n",
                "REFRESH_INTERVAL_SEC = 5*60     # time between refreshes\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {"tags": ["parameters"]},
        },
        {
            "cell_type": "code",
            "source": [
                "# Run Load Test and Refresh Model concurrently\n",
                "import notebookutils\n",
                "from datetime import datetime, timezone\n",
                "\n",
                "# Shared timestamp for correlated log files\n",
                "ts = datetime.now(timezone.utc).astimezone().strftime('%Y%m%d-%H%M%S')\n",
                "load_log = f\"LoadTest.{CONCURRENT_USERS}users.{ts}.csv\"\n",
                "refresh_log = f\"RefreshHistory.{CONCURRENT_USERS}users.{ts}.csv\"\n",
                "\n",
                "# Refresh starts after ramp-up + 1 min steady state\n",
                "refresh_initial_delay = USER_RAMP_TIME_SEC + 60\n",
                "refresh_duration = DURATION_SECONDS - refresh_initial_delay\n",
                "\n",
                "DAG = {\n",
                "    \"activities\": [\n",
                "        {\n",
                "            \"name\": \"LoadTest\",\n",
                "            \"path\": \"Datagen Load Test\",\n",
                "            \"timeoutPerCellInSeconds\": DURATION_SECONDS * 2,\n",
                "            \"args\": {\n",
                "                \"DURATION_SECONDS\": DURATION_SECONDS,\n",
                "                \"USER_RAMP_TIME_SEC\": USER_RAMP_TIME_SEC,\n",
                "                \"CONCURRENT_USERS\": CONCURRENT_USERS,\n",
                "                \"LOG_FILE_NAME\": load_log,\n",
                "            },\n",
                "        },\n",
                "        {\n",
                "            \"name\": \"RefreshModel\",\n",
                "            \"path\": \"Datagen Refresh Model\",\n",
                "            \"timeoutPerCellInSeconds\": DURATION_SECONDS * 2,\n",
                "            \"args\": {\n",
                "                \"INITIAL_DELAY_SEC\": refresh_initial_delay,\n",
                "                \"REFRESH_INTERVAL_SEC\": REFRESH_INTERVAL_SEC,\n",
                "                \"TOTAL_DURATION_SEC\": refresh_duration,\n",
                "                \"LOG_FILE_NAME\": refresh_log,\n",
                "            },\n",
                "        },\n",
                "    ],\n",
                "    \"timeoutInSeconds\": DURATION_SECONDS + 600,\n",
                "    \"concurrency\": 2,\n",
                "}\n",
                "\n",
                "print(f\"Load test: {DURATION_SECONDS}s, {CONCURRENT_USERS} users, ramp {USER_RAMP_TIME_SEC}s\")\n",
                "print(f\"Refresh: starts after {refresh_initial_delay}s, every {REFRESH_INTERVAL_SEC}s, for {refresh_duration}s\")\n",
                "print(f\"Logs: {load_log} / {refresh_log}\")\n",
                "print(\"Starting...\")\n",
                "\n",
                "results = notebookutils.notebook.runMultiple(DAG)\n",
                "\n",
                "print(\"\\nResults:\")\n",
                "for name, result in results.items():\n",
                "    if result.get('exception'):\n",
                "        print(f\"  {name}: FAILED - {result['exception']}\")\n",
                "    else:\n",
                "        print(f\"  {name}: OK\")\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
        # -- Cell 3: Report --
        {
            "cell_type": "code",
            "source": [
                "# Telemetry report — read both CSV logs and chart query performance\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import os, requests\n",
                "import notebookutils\n",
                "import sempy.fabric as _fabric\n",
                "\n",
                "# Get capacity SKU\n",
                "_ws_id = _fabric.resolve_workspace_id()\n",
                "_token = notebookutils.credentials.getToken('pbi')\n",
                "_headers = {'Authorization': f'Bearer {_token}'}\n",
                "try:\n",
                "    _ws_info = requests.get(f'https://api.fabric.microsoft.com/v1/workspaces/{_ws_id}', headers=_headers).json()\n",
                "    _cap_id = _ws_info.get('capacityId', '')\n",
                "    _cap_info = requests.get(f'https://api.fabric.microsoft.com/v1/capacities/{_cap_id}', headers=_headers).json()\n",
                "    _sku = _cap_info.get('sku', '?')\n",
                "    print(f'Capacity: {_sku}  ({_cap_info.get(\"displayName\", \"\")})')\n",
                "except Exception as ex:\n",
                "    _sku = '?'\n",
                "    print(f'Could not get capacity info: {ex}')\n",
                "\n",
                "DATAGEN_DIR = '/lakehouse/default/Files/datagen'\n",
                "LOG_DIR = f'{DATAGEN_DIR}/logs'\n",
                "\n",
                "load_path = f'{LOG_DIR}/{load_log}'\n",
                "refresh_path = f'{LOG_DIR}/{refresh_log}'\n",
                "\n",
                "if not os.path.exists(load_path):\n",
                "    raise FileNotFoundError(f'Load test log not found: {load_log}')\n",
                "else:\n",
                "    df = pd.read_csv(load_path)\n",
                "    print(f'Load test: {len(df)} records  |  Success: {(df.Outcome==\"Success\").sum()}  |  Error: {(df.Outcome==\"Error\").sum()}')\n",
                "\n",
                "    # Compute time buckets\n",
                "    t_min, t_max = df.StartTimeMs.min(), df.StartTimeMs.max()\n",
                "    duration_s = (t_max - t_min) / 1000\n",
                "    n_buckets = min(100, len(df))\n",
                "    df['bucket'] = pd.cut(df.StartTimeMs, bins=n_buckets, labels=False)\n",
                "\n",
                "    ok = df[df.Outcome == 'Success']\n",
                "    err = df[df.Outcome == 'Error']\n",
                "    agg = ok.groupby('bucket').agg(\n",
                "        count=('DurationMs', 'count'),\n",
                "        mean_ms=('DurationMs', 'mean'),\n",
                "        min_ms=('DurationMs', 'min'),\n",
                "        max_ms=('DurationMs', 'max'),\n",
                "        t=('StartTimeMs', 'mean'),\n",
                "    ).reset_index()\n",
                "    err_agg = err.groupby('bucket').agg(err_count=('DurationMs', 'count')).reset_index()\n",
                "    user_agg = df.groupby('bucket').agg(active_users=('ActiveUsers', 'max')).reset_index()\n",
                "    agg = agg.merge(err_agg, on='bucket', how='left').merge(user_agg, on='bucket', how='left').fillna(0)\n",
                "    agg['time_s'] = (agg.t - t_min) / 1000\n",
                "\n",
                "    # Read refresh log for vertical lines\n",
                "    refresh_events = []  # (refresh_start_s, sync_end_s, row)\n",
                "    if os.path.exists(refresh_path):\n",
                "        rdf = pd.read_csv(refresh_path)\n",
                "        print(f'Refreshes: {len(rdf)} recorded')\n",
                "        from dateutil import parser as _dtp\n",
                "\n",
                "        # Map refresh UTC timestamps to chart seconds\n",
                "        # Both load test Timestamp and refresh timestamps are UTC\n",
                "        ts_first = pd.to_datetime(df.Timestamp.iloc[0])\n",
                "        ms_first = df.StartTimeMs.iloc[0]\n",
                "        # test_start_utc = first timestamp minus its elapsed ms\n",
                "        test_start_utc = ts_first - pd.Timedelta(milliseconds=ms_first)\n",
                "        def utc_to_chart(utc_str):\n",
                "            t = pd.Timestamp(_dtp.isoparse(utc_str)).tz_localize(None)\n",
                "            return (t - test_start_utc).total_seconds()\n",
                "\n",
                "        for _, row in rdf.iterrows():\n",
                "            try:\n",
                "                r_start_s = max(0, utc_to_chart(row['RefreshStartUTC']))\n",
                "                r_end_s = None\n",
                "                if pd.notna(row.get('RefreshEndUTC', None)) and str(row.get('RefreshEndUTC', '')).strip():\n",
                "                    r_end_s = max(0, utc_to_chart(row['RefreshEndUTC']))\n",
                "                sync_end_s = None\n",
                "                if pd.notna(row.get('SyncEndUTC', None)) and str(row.get('SyncEndUTC', '')).strip():\n",
                "                    sync_end_s = max(0, utc_to_chart(row['SyncEndUTC']))\n",
                "                refresh_events.append((r_start_s, r_end_s, sync_end_s, row))\n",
                "            except Exception as ex:\n",
                "                print(f'Warning: could not parse refresh row: {ex}')\n",
                "\n",
                "    # Chart \\u2014 3 subplots\n",
                "    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 10), sharex=True,\n",
                "                                        gridspec_kw={'height_ratios': [3, 1, 1]})\n",
                "\n",
                "    # Helper to draw refresh/sync lines on an axis\n",
                "    def draw_refresh_lines(ax, show_legend=False):\n",
                "        for i, (rs, re, se, _) in enumerate(refresh_events):\n",
                "            ax.axvline(x=rs, color='green', linestyle='--', linewidth=1.5, alpha=0.7,\n",
                "                       label='Refresh start' if i == 0 and show_legend else '')\n",
                "            if se is not None:\n",
                "                ax.axvline(x=se, color='red', linestyle=':', linewidth=1.5, alpha=0.7,\n",
                "                           label='Sync complete' if i == 0 and show_legend else '')\n",
                "\n",
                "    # Top: latency\n",
                "    ax1.fill_between(agg.time_s, agg.min_ms, agg.max_ms, alpha=0.15, color='steelblue', label='min\\u2013max')\n",
                "    ax1.plot(agg.time_s, agg.mean_ms, color='steelblue', linewidth=1.5, label='mean')\n",
                "    ax1.plot(agg.time_s, agg.max_ms, color='coral', linewidth=0.8, alpha=0.7, label='max')\n",
                "    draw_refresh_lines(ax1, show_legend=True)\n",
                "    ax1.set_ylabel('Latency (ms)')\n",
                "    ax1.legend(loc='upper left')\n",
                "    ax1.set_title(f'Load Test \\u2014 {len(df)} queries over {duration_s:.0f}s  |  {CONCURRENT_USERS} users  |  {_sku}')\n",
                "    ax1.grid(True, alpha=0.3)\n",
                "\n",
                "    # Middle: throughput\n",
                "    bucket_width = duration_s / n_buckets\n",
                "    ax2.bar(agg.time_s, agg['count'] / bucket_width, width=bucket_width * 0.9,\n",
                "            color='steelblue', alpha=0.6, label='QPS (success)')\n",
                "    if agg.err_count.sum() > 0:\n",
                "        ax2.bar(agg.time_s, agg.err_count / bucket_width, width=bucket_width * 0.9,\n",
                "                bottom=agg['count'] / bucket_width, color='red', alpha=0.6, label='QPS (error)')\n",
                "    draw_refresh_lines(ax2)\n",
                "    ax2.set_ylabel('Queries/sec')\n",
                "    ax2.legend(loc='upper left')\n",
                "    ax2.grid(True, alpha=0.3)\n",
                "\n",
                "    # Bottom: active users\n",
                "    ax3.plot(agg.time_s, agg.active_users, color='green', linewidth=1.5, label='Active users')\n",
                "    ax3.fill_between(agg.time_s, 0, agg.active_users, alpha=0.1, color='green')\n",
                "    draw_refresh_lines(ax3)\n",
                "    ax3.set_ylabel('Users')\n",
                "    ax3.set_xlabel('Time (seconds)')\n",
                "    ax3.legend(loc='upper left')\n",
                "    ax3.grid(True, alpha=0.3)\n",
                "    ax3.set_ylim(bottom=0)\n",
                "\n",
                "    plt.tight_layout()\n",
                "    plt.show()\n",
                "\n",
                "    # Summary stats\n",
                "    print(f'\\nDuration: {duration_s:.1f}s')\n",
                "    print(f'QPS: {(df.Outcome==\"Success\").sum() / duration_s:.1f}')\n",
                "    print(f'Users: {df.UserEmail.nunique()} distinct')\n",
                "    print(f'Latency \\u2014 min: {ok.DurationMs.min():.0f}ms  median: {ok.DurationMs.median():.0f}ms  '\n",
                "          f'mean: {ok.DurationMs.mean():.0f}ms  p95: {ok.DurationMs.quantile(0.95):.0f}ms  '\n",
                "          f'max: {ok.DurationMs.max():.0f}ms')\n",
                "\n",
                "    # Refresh table\n",
                "    if refresh_events:\n",
                "        print(f'\\nRefresh History ({len(refresh_events)} refreshes):')\n",
                "        for rs, re, se, row in refresh_events:\n",
                "            n = int(row.get('RefreshNumber', 0))\n",
                "            r_start_utc = str(row.get('RefreshStartUTC', ''))[:19]\n",
                "            r_end_utc = str(row.get('RefreshEndUTC', ''))[:19]\n",
                "            r_dur = row.get('RefreshDurationSec', '')\n",
                "            s_start_utc = str(row.get('SyncStartUTC', ''))[:19] if pd.notna(row.get('SyncStartUTC')) else ''\n",
                "            s_end_utc = str(row.get('SyncEndUTC', ''))[:19] if pd.notna(row.get('SyncEndUTC')) else ''\n",
                "            s_dur = row.get('SyncDurationSec', '') if pd.notna(row.get('SyncDurationSec')) else ''\n",
                "            status = str(row.get('RefreshStatus', '?'))\n",
                "            rs_t = f'{rs:.0f}s'\n",
                "            re_t = f'{re:.0f}s' if re is not None else ''\n",
                "            se_t = f'{se:.0f}s' if se is not None else ''\n",
                "            print(f'  Refresh #{n}  [{status}]')\n",
                "            print(f'    Refresh: {r_start_utc} \\u2192 {r_end_utc}  ({r_dur}s)  chart t={rs_t} \\u2192 {re_t}')\n",
                "            print(f'    Sync:    {s_start_utc} \\u2192 {s_end_utc}  ({s_dur}s)  chart t={se_t}')\n",
                "    else:\n",
                "        print('\\nNo refreshes recorded')\n",
                "\n",
            ],
            "execution_count": None, "outputs": [], "metadata": {},
        },
    ]

    notebook = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": _PYSPARK_METADATA,
        "cells": cells,
    }

    platform = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "Notebook", "displayName": "Datagen Run Load Test With Refreshes"},
        "config": {"version": "2.0", "logicalId": "44444444-4444-4444-4444-444444444444"},
    }

    with open(os.path.join(nb_dir, "notebook-content.ipynb"), "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    with open(os.path.join(nb_dir, ".platform"), "w", encoding="utf-8") as f:
        json.dump(platform, f, indent=2)

    print(f"Notebook built: {nb_dir}")
    return nb_dir
